apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: uptime-kuma-ingress
  namespace: uptime-kuma
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`uptime.javel.tech`)
      kind: Rule
      services:
        - name: uptime-kuma
          port: 3001
  tls:
    secretName: uptime-kuma-tls
